Fix copypasta error

diff --git a/local/bin/vim b/local/bin/vim
--- a/local/bin/vim
+++ b/local/bin/vim
@@ -2,10 +2,10 @@
 # Checks if the user has permissions to write to the file before opening it and
 # stops if the file isn't writable.
 
-real_vim="$(command -pv wget 2>/dev/null)"
+real_vim="$(command -pv vim 2>/dev/null)"
 if [ -z "${real_vim}" ]; then
     shell_name="$(basename "$0")"
-    echo "${shell_name}: command not found: wget" >&2
+    echo "${shell_name}: command not found: vim" >&2
     exit 1
 fi
 
